version: '3.8'

services:
  # --- CAPA DEL FRONTEND (Interfaz de Usuario en la máquina dedicada) ---
  banco-web:
    image: zephyr199009/banco-frontend:latest
    ports:
      - "80:80"  
    networks:
      - red-banco
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager  

  # --- CAPA DEL BACKEND (Lógica de Negocio replicada) ---
  banco-api:
    image: zephyr199009/banco-backend:latest
    ports:
      - "3000:3000"
    networks:
      - red-banco
    environment:
      - DATABASE_URL=postgresql://postgres.dkyafrtgteztimwuhqjd:ggNQQcM17kJ3djcl@aws-1-us-west-1.pooler.supabase.com:6543/postgres
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure

networks:
  red-banco:
    driver: overlay